name: Build EP Documentation

on:
  push:
    branches:
      - main

jobs:
  build-user-guide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r docs/requirements.txt
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended latexmk

    - name: Build Sphinx User Guide PDF
      run: |
        cd docs
        make latexpdf

    # - name: Upload User Guide PDF
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: user_guide-${{ github.sha }}
    #     path: docs/build/latex

    - name: Move User Guide PDF to _static
      run: |
        mv docs/build/latex/user_guide.pdf docs/source/_static/user_guide.pdf

    - name: Commit and Push User Guide PDF
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/source/_static/user_guide.pdf
        git commit -m "Update user_guide.pdf"
        git push

    - name: Trigger RTDs build
      uses: dfm/rtds-action@v1
      with:
        webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
        webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
        commit_ref: ${{ github.ref }}
