name: Build EP User Guide

on:
  push:
    branches:
      - main

jobs:
  build-user-guide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r docs/requirements.txt
        sudo apt-get update
        sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended latexmk

    - name: Build Sphinx Docs
      run: |
        cd docs
        make latexpdf
        mv build/latex/user_guide.pdf source/_static/

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
