name: Format check
on:
  schedule:
    - cron: "*/15 * * * *" # Run at 12:21am US Eastern time

jobs:
  formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v1
      - name: Install JuliaFormatter and format
        run: |
          julia  -e 'import Pkg; Pkg.add("JuliaFormatter")'
          julia  -e 'using JuliaFormatter; format(".")'
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Format .jl files
          title: 'Automatic JuliaFormatter.jl run'
          branch: auto-juliaformatter-pr
          delete-branch: true
          labels: formatting, automated pr, no changelog
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
          echo "# Format commit SHA:" >> .git-blame-ignore-revs
          git rev-parse HEAD >> .git-blame-ignore-revs
          git config --local user.name GenXProject
          git config --local user.email "84470580+GenXProject@users.noreply.github.com"
          git add .git-blame-ignore-revs; git commit -m "Add commmit to .git-blame-ignore-revs"
          git push origin auto-juliaformatter-pr
