name: PR Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Enforces the update of a changelog file on every pull request
  Changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'Skip-Changelog'
          token: ${{ secrets.GITHUB_TOKEN }}
          missingUpdateErrorMessage: >
            No update to CHANGELOG.md found! Please add a changelog entry
            describing your change with a link to the issue or pull request.
            Please note that the keepachangelog (https://keepachangelog.com)
            format is used. If your change is not applicable for a changelog
            entry, please add the 'Skip-Changelog' label to the pull request.

# Check if the version number in the Project.toml file is updated
  Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version number
        shell: bash {0}
        run: |
          git fetch origin &> /dev/null
          vdiff=$(git diff -U0 origin/{{ github.base_ref }} -- Project.toml | grep -E "^\+" | grep "version =")
          if [ -z "$vdiff" ];
          then
            echo "::error::Error: version number in Project.toml has not been updated." && exit 1

          else
            echo "Version number in Project.toml has been updated."
            echo "New version number:" ${vdiff:1}
          fi